# Generated by Django 6.0.4 on 2026-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
