# Generated by Django 6.0.4 on 2026-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Passwords', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='title',
            field=models.CharField(default='Sin Título', max_length=100),
        ),
        migrations.AddField(
            model_name='pass',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='password',
            field=models.CharField(max_length=512),
        ),
    ]
